version: '3'

networks:
    camagru:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ../app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - camagru

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        expose:
            - "9000"
        volumes:
            - ../app:/var/www/project
        depends_on:
            - mysql8-service
        networks:
            - camagru

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        expose:
            - "3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci    
        restart: always # always restart unless stopped manually
        environment: 
            MYSQL_ROOT_PASSWORD: camagru
            MYSQL_DATABASE: camagru
            MYSQL_HOST: mysql8-service
            MYSQL_USER: ddalee
            MYSQL_USER_PASSWORD: ddaleepwd

        networks:
            - camagru
    
    phpmya:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql8-service
            PMA_USER: ddalee
            PMA_PASSWORD: ddaleepwd
            UPLOAD_LIMIT: 20M
        networks: 
            - camagru
        ports:
            - 8899:80