version: '3'

networks:
    camagru:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - camagru

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        expose:
            - "9000"
        volumes:
            - ./app:/var/www/project
        depends_on:
            - mysql8-service
        networks:
            - camagru

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        expose:
            - "3306"
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: camagru
            MYSQL_DATABASE: camagru
            MYSQL_USER: camagru
            MYSQL_PASSWORD: camagru

        networks:
            - camagru
    
    # adminer
    adminer:
        image: adminer
        container_name: adminer
        environment:
              ADMINER_DEFAULT_SERVER: mysql8-service
              ADMINER_DESIGN: lucas-sandery
        depends_on:
            - mysql8-service
        networks:
            - camagru
        restart: always
        volumes:
            - ./app:/var/www/projet
        ports:
            - "8888:8080"
    
