version: '3'

networks:
    camagru:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "80:80"
        volumes:
            - ../app:/var/www/projet
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        restart: always
        networks:
            - camagru

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        expose:
            - "9000"
        volumes:
            - ../app:/var/www/projet
            - ./php/msmtp/msmtprc:/etc/msmtprc:ro
        depends_on:
            - mysql8-service
        restart: always
        networks:
            - camagru

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        expose:
            - "3306"
        volumes:
            - ../DataMysql:/var/lib/mysql
            # - :/docker-entrypoint-initdb.d/schema.sql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci    
        restart: always # always restart unless stopped manually
        environment: 
            MYSQL_ROOT_PASSWORD: camagru
            MYSQL_DATABASE: camagru_DB
        networks:
            - camagru
    
    phpmya:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql8-service #nom du service mysql
            PMA_PASSWORD: camagru
            UPLOAD_LIMIT: 20M
        depends_on:
            - mysql8-service
        networks: 
            - camagru
        restart: always
        ports:
            - 8888:80